ThreeJSSite/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThreeJSSite.Controllers
{
    public class DataController : Controller
    {
        // GET: Data
        public JsonResult Bags()
        { 
            var jsonResult = new JsonResult();
            jsonResult.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            return jsonResult;
        }
    }
}

ThreeJSSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ThreeJSSite.Controllers
{
    public class HomeController : Controller
    {
        static ItemStateHub hub;

        public ActionResult Index()
        {
            hub = new ItemStateHub();
            Task.Factory.StartNew(async () => 
            {
                await Task.Delay(5000);
                hub.Send(new List<BagPosition> { new BagPosition() {
                    BagId = 1,
                    X = 0,
                    Y = 0,
                    Z = 0
                } });
            });

            return View();
        }

        public void About()
        {
            hub.Send(new List<BagPosition> { new BagPosition() {
                BagId = 1,
                X = 0,
                Y = 0,
                Z = 0
            } });
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ThreeJSSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ThreeJSSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ThreeJSSite/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Example 09.01 - Basic animations</title>
    <script type="text/javascript" src="~/ThreeJSLib/three.js"></script>
    <script type="text/javascript" src="~/ThreeJSLib/jquery-1.9.0.js"></script>
    <script type="text/javascript" src="~/ThreeJSLib/dat.gui.js"></script>
    <script type="text/javascript" src="~/ThreeJSLib/TrackballControls.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <style>
        body {
            /* set margin to 0 and overflow to hidden, to go fullscreen */
            margin: 0;
            overflow: hidden;
        }
    </style>
</head>
<body>
    <!-- Div which will hold the Output -->
    <div id="WebGL-output">
    </div>
    <!-- Javascript code that runs our Three.js examples -->
    <script type="text/javascript">

    // once everything is loaded, we run our Three.js stuff.
    $(function () {
        var clock = new THREE.Clock();

        // create a scene, that will hold all our elements such as objects, cameras and lights.
        var scene = new THREE.Scene();
        // add subtle ambient lighting
        var ambientLight = new THREE.AmbientLight(0x0c0c0c);
        scene.add(ambientLight);

        // add spotlight for the shadows
        var spotLight = new THREE.SpotLight(0x00ffff);
        spotLight.position.set(-40, 60, -10);
        scene.add(spotLight);


        // create a camera, which defines where we're looking at.
        // position and point the camera to the center of the scene
        var camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 1000);
        camera.position.x = -30;
        camera.position.y = 40;
        camera.position.z = 30;
        camera.lookAt(scene.position);

        var trackballControls = new THREE.TrackballControls(camera);
        trackballControls.rotateSpeed = 1.0;
        trackballControls.zoomSpeed = 1.0;
        trackballControls.panSpeed = 1.0;
        trackballControls.staticMoving = true;




        // create a render and set the size
        var renderer = new THREE.WebGLRenderer();
        renderer.setClearColor(new THREE.Color(0xEEEEEE, 1.0));
        renderer.setSize(window.innerWidth, window.innerHeight);

        // add the output of the renderer to the html element
        $("#WebGL-output").append(renderer.domElement);


        //----------------------------static  part------------------------
        // create the ground plane
        var planeGeometry = new THREE.PlaneGeometry(40, 40, 1, 1);
        var planeMaterial = new THREE.MeshLambertMaterial({ color: 0x0000EE });
        var plane = new THREE.Mesh(planeGeometry, planeMaterial);


        // rotate and position the plane
        plane.rotation.x = -0.5 * Math.PI;
        plane.position.x = 0
        plane.position.y = 0
        plane.position.z = 0

        // add the plane to the scene
        scene.add(plane);


        //TODO::get conveyor list from server

        // create a conveyor
        var conveyor1Geometry = new THREE.CubeGeometry(8, .5, 4);
        var conveyor1Material = new THREE.MeshLambertMaterial({ color: 0x00ffff });
        var conveyor1 = new THREE.Mesh(conveyor1Geometry, conveyor1Material);
        // position the conveyor
        conveyor1.position.x = -(40 / 2) + 4;
        conveyor1.position.y = .25;
        conveyor1.position.z = 18;
        // add the conveyor to the scene
        scene.add(conveyor1);

        // create a conveyor
        var conveyor2Geometry = new THREE.CubeGeometry(8, .5, 4);
        var conveyor2Material = new THREE.MeshLambertMaterial({ color: 0x00ffff });
        var conveyor2 = new THREE.Mesh(conveyor1Geometry, conveyor1Material);
        // position the conveyor
        conveyor2.position.x = -(40 / 2) + 4 + 8.1;
        conveyor2.position.y = .25;
        conveyor2.position.z = 18;
        // add the conveyor to the scene
        scene.add(conveyor2);
        //----------------------------------------------------------------


        //----------------------------dynamic part------------------------
        var bags = [];
        bags = GetBags();
        bags.forEach(function (bag) {
            scene.add(bag.value);
        });
        //----------------------------------------------------------------


        // call the render function
        render();

        function render() {
            var delta = clock.getDelta();
            trackballControls.update(delta);

            //TODO::receive position update from server by SignalR
            bags.forEach(function (bag) {
                bag.value.position.x += .01;
            });

            // render using requestAnimationFrame
            renderer.render(scene, camera);
            requestAnimationFrame(render);

        }


        function GetBags() {
            var bags = [];

            $.getJSON('@Url.Action("Bags", "Data")', function (result) {
                console.debug("dd");
                //bags = result;
            });

            for (var i = 0; i < 3; i++) {
                // create a cube
                var bagGeometry = new THREE.CubeGeometry(2, 2, 2);
                var bagMaterial = new THREE.MeshLambertMaterial({ color: 0x00ff00 });
                var bag = new THREE.Mesh(bagGeometry, bagMaterial);

                // position the cube
                bag.position.x = -(40 / 2) + 1 + 5 * i;
                bag.position.y = 1 + .5;
                bag.position.z = 18;

                // add the cube to the scene
                bags.push({
                    key: i,
                    value: bag
                });
            }

            return bags;
        }




        $.connection.hub.start();
        var itemStates = $.connection.itemStateHub;
        itemStates.client.updateBagPosition = function (bagPositions) {
            bagPositions.forEach(function (bagPosition) {
                bags.forEach(function (bag)
                {
                    if (bag.key == bagPosition.BagId) {
                        bag.value.position.x = bagPosition.X;
                        bag.value.position.y = bagPosition.Y;
                        bag.value.position.z = bagPosition.Z;
                    }
                })

            });
        };
    });


    </script>
</body>
</html>